### PR TITLE
Updated slideshow for Ubuntu Budgie

### PR DESCRIPTION
**Pull request by GrindamN**
This update allows for slideshow to be cleaner and more up to date in terms of current Ubuntu Budgie release.

### CODE REVIEW

**Comment by fossfreedom** [comment]
Some initial issues:

 - the second slide as the desktop time - we should remove that otherwise we have to keep updating each release
 - Raven is the wrong side for the default - should be right side
 - the image looks a bit squeezed rather than the expected dimensions
 - the music slide - kinetic doesn't ship rhythmbox and celluloid.  Now we ship lollypop, gpodder for podcasts, goodvibes for internet radiostations and parole for videos
 - libreoffice image is out of date
 - gnome-software image is out of date
 - the browser image is stretched so looks odd

**Comment by GrindamN** [comment]
* Agreed
* Agreed
* Yeah, I have problem with resizing since Sinc is no longer available for option when scaling and for some reason it ends up being square.
* okay, the music part will be changed
* as for libreoffice icon, I'm not sure what icon we can use that shows the entire office suite. I can add the one from Docs or Calc if it is okay.
* Gnome-software - will update
* Yeah same issues with scaling as above.

**Comment by fossfreedom** [comment]
... I was referring to the libreoffice writer image - the icon is probably ok.

For the screenshot images I would use a virtualbox / qemu or similar and make sure the screen is kind of squarish before grabbing the screenshot.  That way the image is the right shape.  Either that or use a monitor that is the old style square shape rather than the normal letterbox size now.

**Comment by fossfreedom** [comment]
nicely done.

Just the music & videos slide is wrong for kinetic

**Comment by fossfreedom** [comment]
The words on the media slide is wrong  - suggest applying this diff

```
diff --git a/slideshows/ubuntu-budgie/slides/05_media.html b/slideshows/ubuntu-budgie/slides/05_media.html
index 8b58e67..aa7420b 100644
--- a/slideshows/ubuntu-budgie/slides/05_media.html
+++ b/slideshows/ubuntu-budgie/slides/05_media.html
@@ -5,9 +5,13 @@
 <div class="main">
        <div class="text">
                <div>
-                       <p><strong>Rhythmbox</strong> lets you organize your music and listen to Internet radio, podcasts, and more.</p>
+                       <p><strong>Lollypop</strong> lets you organize your music.</p>
                        <br />
-                       <p><strong>Celluloid</strong> allows you to easily watch videos from your computer or DVD.</p>
+                       <p><strong>Parole</strong> allows you to easily watch videos from your computer or DVD.</p>
+                       <br />
+                       <p>Listen to podcasts through the excellent <strong>gPodder</strong>.</p>
+                       <br />
+                       <p>Play internet radio via <strong>Goodvibes</strong>.</p>
                </div>
 
                <div class="bigicon">
```


What is this folder? ubuntu-budgie/slides/link/backup/

**Comment by GrindamN** [comment]
Done. The backup folder was there when I was testing out the CSS for the arrows. I have added the corresponding text to the icons and also removed old icons to saves pace as well some stuff that was left there and not needed.

**Pull request merged**
